project:
  type: website
  output-dir: docs

website:
  favicon: img/tactic.ico
  title: "Innovalab"
  twitter-card: 
    image: "https://raw.githubusercontent.com/healthinnovation/Harmonize-Project/main/img/twitter-card.png"
    creator: "@antony_barja"
    site: "@antony_barja"
  open-graph:
    description: "TACTIC-PERU"
    image: "https://raw.githubusercontent.com/healthinnovation/Harmonize-Project/main/img/twitter-card.png"
  navbar:
    logo: img/TACTIC_LOGO_white.png
    left:
      - href: index.qmd
        text: Home
      - href: webmap.qmd
        text: Webmap
        target: _blank
    right:
      - icon: github
        href: https://github.com/healthinnovation/tactic-visor
      - icon: twitter
        href: https://twitter.com/innovalab_imt
  
format:
  html:
    theme: cosmo
    css: css/style.css
    toc: true

editor: visual
